import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Home, Users, Trophy, ArrowLeftRight, Landmark, ChevronRight, Flame, Snowflake, CircleDollarSign, Play, FastForward, RotateCcw, Save, ShieldCheck, Sparkles, Swords, X, Plus, Minus, Menu, Award, History, UserRound, Gauge, CircleDot, GripVertical } from 'lucide-react';
import { CAP, POSITIONS, BAT_TRAITS, PITCH_TRAITS, makeLeague, scheduleFor, teamPayroll, rating, potential, fullTeamName, bestLineup, chooseCandidates, validRoster, makePlayer, philosophies, teamNames } from './data.js';
import { makeGame, currentMatchup, stepPlateAppearance, simulateUntil, fatigueState, substitutePitcher, substituteBatter, quickGame, preparePitch, resolvePitch } from './sim.js';

const SAVE_KEY='pennant-panic-save-v1';
const navItems=[['home','Home',Home],['roster','Roster',Users],['league','League',Trophy],['market','Market',ArrowLeftRight],['club','Club',Landmark]];
const POSITION_ORDER=['SP','RP','C','1B','2B','3B','SS','LF','CF','RF','DH'];
const fmtTrait=t=>t[0].toUpperCase()+t.slice(1);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const positionRank=p=>{const i=POSITION_ORDER.indexOf(p.position);return i<0?POSITION_ORDER.length:i};
const byPosition=(a,b)=>positionRank(a)-positionRank(b)||rating(b)-rating(a)||a.name.localeCompare(b.name);
const positionsLabel=p=>[p.position,...(p.secondary||[])].join('/');
const potentialRange=p=>`${clamp(potential(p)-4,20,99)}–${clamp(potential(p)+3,20,99)}`;
const BALLPARKS=[
  {id:'balanced',icon:'◆',name:'The Panic Grounds',note:'A fair park with no hidden edge.',effect:'Balanced baseball.'},
  {id:'short-porch',icon:'↗',name:'The Short Porch',note:'The walls are suspiciously close.',effect:'+8 power for every hitter at home.'},
  {id:'endless',icon:'∞',name:'The Endless Outfield',note:'Outfielders may need provisions.',effect:'−8 power and +10 speed at home.'},
  {id:'rocket-mound',icon:'▲',name:'The Rocket Mound',note:'Pitchers appear to be launching downhill.',effect:'+6 velocity, but fatigue bites harder.'}
];
const ARTIFACTS=[
  {id:'corked-bat',icon:'⚡',name:'Corked Heirloom Bat',note:'+10 power, −5 contact.',roles:['BAT']},
  {id:'illegal-curve',icon:'◎',name:"Grandpa's Illegal Curve",note:'+10 spin, −5 control.',roles:['SP','RP']},
  {id:'possessed-cleats',icon:'↯',name:'Possessed Cleats',note:'+12 speed, but cold days hit harder.',roles:['BAT']},
  {id:'golden-lunchbox',icon:'✦',name:'Golden Lunchbox',note:'+3 to every skill while a bonded partner plays.',roles:['BAT']}
];
const SIGNATURES={
  BAT:[{id:'walk-machine',name:'Walk Machine',note:'+10 eye in games.'},{id:'two-out-menace',name:'Two-Out Menace',note:'+8 contact with two outs.'},{id:'extra-base-goblin',name:'Extra-Base Goblin',note:'+10 power after making contact.'}],
  PITCH:[{id:'strikeout-artist',name:'Strikeout Artist',note:'+9 velocity in games.'},{id:'walk-eraser',name:'Walk Eraser',note:'+10 control in games.'},{id:'spin-wizard',name:'Spin Wizard',note:'+9 spin in games.'}]
};
const artifactById=id=>ARTIFACTS.find(a=>a.id===id);
const createDuo=team=>{const pool=team.roster.filter(p=>p.role==='BAT').sort((a,b)=>b.tenure-a.tenure||rating(b)-rating(a)).slice(0,8);if(pool.length<2)return null;return{id:`duo-${pool[0].id}-${pool[1].id}`,players:[pool[0].id,pool[1].id],name:['The Breakfast Club','The Dugout Goblins','The Double Trouble Department','The Sauce Brothers'][team.id%4],note:'Both hitters gain +3 while they appear in the same game.'}};
function migrateState(raw){if(!raw)return raw;const x=raw;x.league?.teams?.forEach((team,i)=>Object.assign(team,{colors:teamNames[i]?.colors||team.colors,mark:teamNames[i]?.mark||team.mark}));x.bossSeriesEnabled??=true;x.ballparkId??='balanced';x.cornerstoneId??=null;x.cornerstoneYear??=null;x.artifacts??={inventory:['corked-bat','golden-lunchbox'],equipped:{}};x.artifacts.inventory??=['corked-bat','golden-lunchbox'];x.artifacts.equipped??={};x.bonds??=[];const team=x.league?.teams?.[x.userId];x.bonds=x.bonds.filter(d=>d.players.every(id=>team?.roster.find(p=>p.id===id)?.role==='BAT'));if(team&&!x.bonds.length){const duo=createDuo(team);if(duo)x.bonds=[duo]}if(x.schedule?.length&&!x.schedule.some(s=>s.boss)){const idx=Math.min(x.schedule.length-1,Math.max((x.seriesIndex||0)+1,3));x.schedule[idx].boss={id:'wall',name:'THE WALL',note:'Every opposing pitcher gains spin and control.',reward:'golden-lunchbox'};x.schedule[idx].userWins??=0}return x}
const statOf=p=>{const s={g:0,pa:0,ab:0,h:0,doubles:0,triples:0,hr:0,r:0,rbi:0,bb:0,so:0,ipOuts:0,er:0,hitsAllowed:0,bbAllowed:0,k:0,...(p?.stats||{})};if(s.ab<s.h||(!s.ab&&s.pa))s.ab=Math.max(s.h,s.pa-s.bb);return s};
const pct=n=>Number.isFinite(n)?n.toFixed(3).replace(/^0/,''):'---';
const battingAvg=p=>{const s=statOf(p);return s.ab?pct(s.h/s.ab):'---'};
const playerOps=p=>{const s=statOf(p);if(!s.pa||!s.ab)return '---';const obp=(s.h+s.bb)/s.pa,tb=s.h+s.doubles+s.triples*2+s.hr*3;return pct(obp+tb/s.ab)};
const playerEra=p=>{const s=statOf(p);return s.ipOuts?(s.er*27/s.ipOuts).toFixed(2):'—'};
const playerWhip=p=>{const s=statOf(p);return s.ipOuts?((s.hitsAllowed+s.bbAllowed)*3/s.ipOuts).toFixed(2):'—'};
const innings=p=>{const o=statOf(p).ipOuts;return `${Math.floor(o/3)}.${o%3}`};
const rollLeagueForm=teams=>teams.map(t=>({...t,roster:t.roster.map(p=>({...p,form:Math.random()<.09?'hot':Math.random()<.18?'cold':'neutral'}))}));

function teamStatLine(team){
  const bats=team.roster.filter(p=>p.role==='BAT').map(statOf),arms=team.roster.filter(p=>p.role!=='BAT').map(statOf);
  const sum=(rows,key)=>rows.reduce((n,s)=>n+(s[key]||0),0),ab=sum(bats,'ab'),pa=sum(bats,'pa'),h=sum(bats,'h'),bb=sum(bats,'bb'),tb=h+sum(bats,'doubles')+sum(bats,'triples')*2+sum(bats,'hr')*3,outs=sum(arms,'ipOuts');
  return {avg:ab?pct(h/ab):'---',hr:sum(bats,'hr'),ops:ab&&pa?pct((h+bb)/pa+tb/ab):'---',k:sum(arms,'k'),whip:outs?((sum(arms,'hitsAllowed')+sum(arms,'bbAllowed'))*3/outs).toFixed(2):'—',era:outs?(sum(arms,'er')*27/outs).toFixed(2):'—'};
}

function applyQuickStats(team,runs,allowed){
  const batters=team.roster.filter(p=>p.role==='BAT').sort(()=>Math.random()-.5).slice(0,9),hits=clamp(Math.round(6+runs*.75+(Math.random()-.5)*4),3,16),homers=Math.min(runs,Math.floor(Math.random()*3));
  batters.forEach((p,i)=>{p.stats={...statOf(p)};const pa=i<3?5:4,walk=Math.random()<.22?1:0;p.stats.g++;p.stats.pa+=pa;p.stats.ab+=pa-walk;p.stats.bb+=walk;p.stats.so+=Math.random()<.3?2:Math.random()<.65?1:0;});
  for(let i=0;i<hits;i++){const p=batters[i%batters.length];p.stats.h++;if(i<homers){p.stats.hr++;p.stats.rbi+=Math.max(1,Math.min(3,runs-homers+1));}}
  const starter=team.roster.filter(p=>p.role==='SP')[(team.wins+team.losses)%4],s=starter.stats={...statOf(starter)};s.g++;s.ipOuts+=27;s.er+=allowed;s.hitsAllowed+=clamp(Math.round(6+allowed*.7),3,16);s.bbAllowed+=Math.floor(Math.random()*4);s.k+=4+Math.floor(Math.random()*7);
}

const tradeScore=p=>rating(p)*.55+potential(p)*.34+Math.max(0,29-p.age)*.45-p.salary*.48;
function evaluateTrade(ourPlayer,theirPlayer,otherTeam){
  if(!ourPlayer||!theirPlayer)return null;
  const offered=tradeScore(ourPlayer),asked=tradeScore(theirPlayer),capOk=teamPayroll(otherTeam)-theirPlayer.salary+ourPlayer.salary<=CAP,roleOk=ourPlayer.role===theirPlayer.role;
  const reasons=[];
  const overallDelta=rating(ourPlayer)-rating(theirPlayer),futureDelta=potential(ourPlayer)-potential(theirPlayer),salaryDelta=theirPlayer.salary-ourPlayer.salary;
  reasons.push(overallDelta>=3?`They gain ${overallDelta} current-rating points.`:overallDelta<=-3?`They lose ${Math.abs(overallDelta)} current-rating points.`:'Current ability is roughly even.');
  reasons.push(futureDelta>=4?`They gain ${futureDelta} potential points.`:futureDelta<=-4?`They give up ${Math.abs(futureDelta)} potential points.`:'Long-term upside is similar.');
  reasons.push(salaryDelta>=3?`They save ${salaryDelta}M in salary.`:salaryDelta<=-3?`Their payroll rises ${Math.abs(salaryDelta)}M.`:'Salary impact is small.');
  if(!roleOk)reasons.unshift('The roster roles do not match.');
  if(!capOk)reasons.unshift('This would put them over the salary cap.');
  const accepted=roleOk&&capOk&&offered>=asked-1;
  const margin=offered-(asked-1);
  return {offered,asked,capOk,roleOk,accepted,margin,reasons,label:!roleOk?'Illegal roster fit':!capOk?'Blocked by their cap':margin>=6?'Strong chance to accept':margin>=0?'Likely to accept':margin>=-4?'Close, but likely decline':'Likely to decline'};
}

function initialState(teamId,philosophyId){
  const league=makeLeague();
  const duo=createDuo(league.teams[teamId]);
  return { league,userId:teamId,year:1,schedule:scheduleFor(teamId,league.teams),seriesIndex:0,gameInSeries:0,phase:'hub',nav:'home',
    philosophyId, lineup:bestLineup(league.teams[teamId]), starterId:null, usedStarters:[], game:null, prep:null,
    history:[], news:[`You purchased the ${fullTeamName(league.teams[teamId])}. Try not to ruin them.`], legacy:0, postseason:null,
    rivalRecord:{wins:0,losses:0}, settings:{dramaticStops:true},bossSeriesEnabled:true,ballparkId:'balanced',cornerstoneId:null,cornerstoneYear:null,
    artifacts:{inventory:['corked-bat','golden-lunchbox'],equipped:{}},bonds:duo?[duo]:[] };
}

function App(){
  const [state,setState]=useState(()=>{try{return migrateState(JSON.parse(localStorage.getItem(SAVE_KEY))||null)}catch{return null}});
  const [detail,setDetail]=useState(null);
  const [toast,setToast]=useState('');
  useEffect(()=>{if(state)localStorage.setItem(SAVE_KEY,JSON.stringify(state));},[state]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
  if(!state)return <Setup onStart={(team,phil)=>setState(initialState(team,phil))}/>;
  const team=state.league.teams[state.userId];
  const opponent=state.schedule[state.seriesIndex] ? state.league.teams[state.schedule[state.seriesIndex].opponentId] : null;
  const updateTeam=(teamId,fn)=>setState(s=>({...s,league:{...s.league,teams:s.league.teams.map(t=>t.id===teamId?fn(structuredClone(t)):t)}}));
  const openPlayer=id=>setDetail(state.league.teams.flatMap(t=>t.roster).concat(state.league.freeAgents,state.offseason?.prospects||[]).find(p=>p.id===id));
  const go=n=>setState(s=>({...s,nav:n}));
  let content;
  if(state.phase.startsWith('prep-')) content=<Prep state={state} setState={setState} team={team} opponent={opponent} openPlayer={openPlayer} toast={setToast}/>;
  else if(state.phase==='lineup') content=<Lineup state={state} setState={setState} team={team} opponent={opponent} openPlayer={openPlayer}/>;
  else if(state.phase==='game') content=<Game state={state} setState={setState} openPlayer={openPlayer} toast={setToast}/>;
  else if(state.phase==='season-end') content=<SeasonEnd state={state} setState={setState}/>;
  else if(state.phase.startsWith('offseason')) content=<Offseason state={state} setState={setState} openPlayer={openPlayer} toast={setToast}/>;
  else content={home:<Hub state={state} setState={setState} team={team} opponent={opponent} openPlayer={openPlayer}/>,roster:<Roster team={team} openPlayer={openPlayer}/>,league:<League state={state} openPlayer={openPlayer}/>,market:<Market state={state} setState={setState} openPlayer={openPlayer} toast={setToast}/>,club:<Club state={state} setState={setState}/>}[state.nav];
  const immersive=state.phase!=='hub';
  return <div className="app-shell" style={{'--team-primary':team.colors[0],'--team-secondary':team.colors[1]}}>
    <header className="topbar"><TeamMark team={team}/><div><div className="eyebrow">YOUR CLUB · YEAR {state.year} · {team.league}</div><strong>{team.city} <span>{team.name}</span></strong></div><div className="top-record"><b>{team.wins}–{team.losses}</b><small>{teamPayroll(team)}/{CAP}M</small></div></header>
    <main className={immersive?'immersive':''}>{content}</main>
    {!immersive&&<nav className="bottom-nav">{navItems.map(([id,label,Icon])=><button className={state.nav===id?'active':''} onClick={()=>go(id)} key={id}><Icon/><span>{label}</span></button>)}</nav>}
    {detail&&<PlayerSheet player={detail} team={state.league.teams.find(t=>t.id===detail.teamId)} state={state} onClose={()=>setDetail(null)}/>} 
    {toast&&<div className="toast">{toast}</div>}
  </div>;
}

function Setup({onStart}){
  const [step,setStep]=useState(0),[teamId,setTeamId]=useState(0),[phil,setPhil]=useState('balanced');
  return <div className="setup"><div className="setup-glow"/><div className="logo-ball">PP</div><p className="kicker">AN ARCADE FRANCHISE SIM</p><h1>Pennant<br/><em>Panic</em></h1>
    {step===0?<><p className="setup-copy">Build a weird little dynasty. Make brutal roster calls. Win the whole ridiculous thing.</p><button className="primary xl" onClick={()=>setStep(1)}>Buy a franchise <ChevronRight/></button><button className="text-btn" onClick={()=>{const raw=localStorage.getItem(SAVE_KEY);if(raw)location.reload()}}>Continue saved game</button></>:
    step===1?<div className="setup-panel"><div className="step-label">01 / PICK YOUR CLUB</div><div className="team-grid">{teamNames.map((t,i)=><button key={i} onClick={()=>setTeamId(i)} className={teamId===i?'selected':''}><TeamMark team={{...t,id:i}}/><b>{t.city} {t.name}</b><small>{i<10?'CIRCUIT A':'CIRCUIT B'}</small></button>)}</div><button className="primary" onClick={()=>setStep(2)}>Choose a philosophy <ChevronRight/></button></div>:
    <div className="setup-panel"><div className="step-label">02 / PICK YOUR STYLE</div><div className="philosophy-list">{philosophies.map(p=><button key={p.id} onClick={()=>setPhil(p.id)} className={phil===p.id?'selected':''}><i>{p.icon}</i><span><b>{p.name}</b><small>{p.benefit} {p.drawback}</small></span></button>)}</div><button className="primary" onClick={()=>onStart(teamId,phil)}>Open the gates <Play/></button></div>}
  </div>
}

function Hub({state,setState,team,opponent,openPlayer}){
  const series=state.schedule[state.seriesIndex]; const ranked=[...state.league.teams.filter(t=>t.league===team.league)].sort((a,b)=>b.wins-a.wins||a.losses-b.losses); const rank=ranked.findIndex(t=>t.id===team.id)+1;
  const hot=team.roster.filter(p=>p.form==='hot'),cold=team.roster.filter(p=>p.form==='cold');
  const startPrep=()=>setState(s=>{
    const existing=s.prep?.seriesIndex===s.seriesIndex?s.prep:null;
    if(existing){
      const devCommitted=existing.devCommitted??Boolean(existing.trade),declineCommitted=existing.declineCommitted??Boolean(existing.trade),tradeResolved=existing.tradeResolved??(Boolean(existing.trade)&&s.nav==='market');
      const prep={...existing,devCommitted,declineCommitted,tradeResolved},phase=tradeResolved?'prep-roster':declineCommitted?'prep-trade':devCommitted?'prep-decline':'prep-develop';
      return {...s,prep,phase};
    }
    const currentTeam=s.league.teams[s.userId],dev=chooseCandidates(currentTeam,'develop'),decline=chooseCandidates(currentTeam,'decline'),gap=CAP-teamPayroll(currentTeam);
    let points=clamp(4+Math.floor(gap/12),4,12);if(s.philosophyId==='value')points=Math.round(points*1.25);
    const jackpotCandidates=dev.map((c,i)=>({c,i,pl:currentTeam.roster.find(p=>p.id===c.playerId)})).filter(x=>!x.pl.signature),jackpotPick=jackpotCandidates.length&&Math.random()<2/3?jackpotCandidates[Math.floor(Math.random()*jackpotCandidates.length)]:null;
    const sigPool=jackpotPick?SIGNATURES[jackpotPick.pl.role==='BAT'?'BAT':'PITCH']:[],signature=jackpotPick?sigPool[Math.floor(Math.random()*sigPool.length)]:null;
    return {...s,phase:'prep-develop',prep:{seriesIndex:s.seriesIndex,dev,decline,devPool:points,devSpent:{},devCommitted:false,declinePool:s.philosophyId==='now'?5:4,declineSpent:{},declineCommitted:false,trade:null,tradeResolved:false,jackpot:jackpotPick?{index:jackpotPick.i,signature}:null}};
  });
  return <div className="page hub-page"><section className="hero-card"><div className="series-opponent">{opponent&&<TeamMark team={opponent} size="large"/>}<div><span className="eyebrow">NEXT · SERIES {state.seriesIndex+1} OF 8</span><h2>{series?.home?'HOST':'AT'} {opponent?fullTeamName(opponent):'Season complete'}</h2><p>{opponent?.league} · Four games · {opponent?.id===team.rivalId?'RIVALRY SERIES':'Regular season'}</p></div></div><div className="series-badge"><b>{series?.played||0}</b><span>/ 4</span></div></section>
    {series?.boss&&state.bossSeriesEnabled&&<div className={`boss-alert ${series.boss.id}`}><Swords/><span><small>BOSS SERIES</small><b>{series.boss.name}</b><p>{series.boss.note} Win 3 games to steal its artifact.</p></span></div>}
    <button className="primary wide" disabled={!opponent} onClick={startPrep}><span>Prepare for the series</span><ChevronRight/></button>
    <div className="quick-stats"><div><small>LEAGUE</small><b>#{rank}</b><span>{team.wins}–{team.losses}</span></div><div><small>PAYROLL</small><b>{teamPayroll(team)}M</b><span>{CAP-teamPayroll(team)}M space</span></div><div><small>LEGACY</small><b>{state.legacy}</b><span>{team.history.championships} titles</span></div></div>
    <SectionTitle label="Clubhouse temperature" action="View roster"/>
    <div className="temperature-row">{hot.length+ cold.length===0?<div className="empty-compact"><CircleDot/> Everyone is steady. New form is rolled before each game.</div>:[...hot,...cold].slice(0,4).map(p=><button className={`mini-player ${p.form}`} key={p.id} onClick={()=>openPlayer(p.id)}>{p.form==='hot'?<Flame/>:<Snowflake/>}<span><b>{p.name}</b><small>{p.position} · {rating(p)} OVR</small></span></button>)}</div>
    {state.bonds?.[0]&&<DuoCard duo={state.bonds[0]} team={team}/>} 
    <SectionTitle label="From the wire"/><div className="news-card">{state.news.slice(0,3).map((n,i)=><p key={i}><span>{String(i+1).padStart(2,'0')}</span>{n}</p>)}</div>
  </div>
}

function Prep({state,setState,team,opponent,openPlayer,toast}){
  const [showRoster,setShowRoster]=useState(false);
  const p=state.prep; const phase=state.phase;
  const back=()=>setState(s=>({...s,phase:'hub'}));
  if(phase==='prep-develop'){
    const left=p.devPool-Object.values(p.devSpent).reduce((a,b)=>a+b,0);
    const add=(i,n)=>setState(s=>{const x=structuredClone(s);const cur=x.prep.devSpent[i]||0;x.prep.devSpent[i]=clamp(cur+n,0,cur+left);return x});
    const recommend=()=>setState(s=>{const x=structuredClone(s);x.prep.devSpent={};for(let i=0;i<p.devPool;i++){const idx=i%4;x.prep.devSpent[idx]=(x.prep.devSpent[idx]||0)+1}return x});
    const confirm=()=>{if(left||p.devCommitted)return;setState(s=>{const x=structuredClone(s);const t=x.league.teams[x.userId],prep=x.prep;prep.dev.forEach((c,i)=>{const pl=t.roster.find(z=>z.id===c.playerId);let gain=prep.devSpent[i]||0;if(s.philosophyId==='mash'&&c.trait==='power')gain=Math.ceil(gain*1.25);if(s.philosophyId==='control'&&c.trait==='control')gain=Math.ceil(gain*1.25);if(s.philosophyId==='youth'&&pl.age<25)gain=Math.ceil(gain*1.25);const breakthrough=Math.random()<.08?2:0;pl[c.trait]=Math.min(pl[`${c.trait}Pot`],pl[c.trait]+gain+breakthrough);pl.development+=gain;if(breakthrough)x.news.unshift(`${pl.name} had a breakthrough in ${fmtTrait(c.trait)} training.`);if(prep.jackpot?.index===i&&gain>=3&&!pl.signature){pl.signature=prep.jackpot.signature;x.news.unshift(`${pl.name} unlocked ${pl.signature.name}.`)}if(pl.age<26&&Math.random()<.035){pl[`${c.trait}Pot`]=Math.min(99,pl[`${c.trait}Pot`]+2);x.news.unshift(`${pl.name}'s ${fmtTrait(c.trait)} ceiling just moved higher.`)}if(pl.role==='BAT'&&pl.secondary.length<2&&Math.random()<.025){const pos=POSITIONS.find(pos=>pos!==pl.position&&!pl.secondary.includes(pos));if(pos){pl.secondary.push(pos);x.news.unshift(`${pl.name} learned ${pos} during cross-training.`)}}});prep.devCommitted=true;x.phase='prep-decline';return x});};
    return <Flow title="Development lab" step="1 OF 4" onBack={back} aside={<button className="text-btn orange" onClick={recommend}>Recommend</button>}><p className="flow-copy">Invest every point. Younger players and bigger potential gaps rise to the top.</p><Pool value={left} label="POINTS LEFT"/>
      <div className="choice-stack">{p.dev.map((c,i)=>{const pl=team.roster.find(z=>z.id===c.playerId),amt=p.devSpent[i]||0;return <Choice key={pl.id} player={pl} trait={c.trait} amount={amt} jackpot={p.jackpot?.index===i?p.jackpot.signature:null} onOpen={()=>openPlayer(pl.id)} onMinus={()=>add(i,-1)} onPlus={()=>left&&add(i,1)} plus/>})}</div><button className="primary wide" disabled={left!==0} onClick={confirm}>Lock in training <ChevronRight/></button></Flow>
  }
  if(phase==='prep-decline'){
    const used=Object.values(p.declineSpent).reduce((a,b)=>a+b,0),left=p.declinePool-used;
    const add=(i,n)=>setState(s=>{const x=structuredClone(s);const cur=x.prep.declineSpent[i]||0;x.prep.declineSpent[i]=clamp(cur+n,0,cur+left);return x});
    const recommend=()=>setState(s=>{const x=structuredClone(s);x.prep.declineSpent={};for(let i=0;i<p.declinePool;i++){const idx=i%4;x.prep.declineSpent[idx]=(x.prep.declineSpent[idx]||0)+1}return x});
    const confirm=()=>{if(left||p.declineCommitted)return;setState(s=>{const x=structuredClone(s),t=x.league.teams[x.userId],prep=x.prep;prep.decline.forEach((c,i)=>{const pl=t.roster.find(z=>z.id===c.playerId);pl[c.trait]=Math.max(20,pl[c.trait]-(prep.declineSpent[i]||0));});prep.declineCommitted=true;x.phase='prep-trade';prep.trade=prep.trade||makeTradeOffer(x);return x});};
    return <Flow title="Hard choices" step="2 OF 4" onBack={back} aside={<button className="text-btn orange" onClick={recommend}>Recommend</button>}><p className="flow-copy">Training is locked in. Time always collects; choose exactly where the club loses ground.</p><Pool value={left} label="DECLINE LEFT" danger/><div className="choice-stack">{p.decline.map((c,i)=>{const pl=team.roster.find(z=>z.id===c.playerId),amt=p.declineSpent[i]||0;return <Choice key={pl.id} player={pl} trait={c.trait} amount={amt} onOpen={()=>openPlayer(pl.id)} onMinus={()=>add(i,-1)} onPlus={()=>left&&add(i,1)} danger/>})}</div><button className="primary wide" disabled={left!==0} onClick={confirm}>Accept the damage <ChevronRight/></button></Flow>
  }
  if(phase==='prep-trade'){
    const tr=p.trade,ours=team.roster.find(z=>z.id===tr.ours),theirs=state.league.teams[tr.teamId].roster.find(z=>z.id===tr.theirs),other=state.league.teams[tr.teamId];
    const decide=accept=>setState(s=>{const x=structuredClone(s);if(x.prep.tradeResolved)return x;if(accept){const a=x.league.teams[x.userId],b=x.league.teams[tr.teamId],pa=a.roster.find(z=>z.id===tr.ours),pb=b.roster.find(z=>z.id===tr.theirs);a.roster=a.roster.filter(z=>z.id!==pa.id);b.roster=b.roster.filter(z=>z.id!==pb.id);pa.teamId=b.id;pb.teamId=a.id;pa.previousTeams.push(a.id);pb.previousTeams.push(b.id);a.roster.push(pb);b.roster.push(pa);x.news.unshift(`Trade complete: ${pb.name} joins the club from ${b.city}.`)}x.prep.tradeResolved=true;x.phase='prep-roster';return x});
    return <><Flow title="Incoming offer" step="3 OF 4" onBack={back} aside={<button className="text-btn roster-peek" onClick={()=>setShowRoster(true)}><Users/> My roster</button>}><div className="trade-from"><TeamMark team={other}/><span><small>OFFER FROM</small><b>{fullTeamName(other)}</b></span></div><div className="trade-board"><TradePlayer label="YOU RECEIVE" player={theirs} onOpen={()=>openPlayer(theirs.id)}/><div className="trade-arrow"><ArrowLeftRight/></div><TradePlayer label="YOU SEND" player={ours} onOpen={()=>openPlayer(ours.id)}/></div><div className="trade-delta"><span>Overall <b className={rating(theirs)>=rating(ours)?'pos':'neg'}>{rating(theirs)-rating(ours)>=0?'+':''}{rating(theirs)-rating(ours)}</b></span><span>Payroll <b className={theirs.salary<=ours.salary?'pos':'neg'}>{theirs.salary-ours.salary>=0?'+':''}{theirs.salary-ours.salary}M</b></span><span>Potential <b>{potential(theirs)-potential(ours)>=0?'+':''}{potential(theirs)-potential(ours)}</b></span></div><button className="primary wide" disabled={teamPayroll(team)-ours.salary+theirs.salary>CAP} onClick={()=>decide(true)}>Accept trade</button><button className="secondary wide" onClick={()=>decide(false)}>No deal</button></Flow>{showRoster&&<RosterOverlay team={team} onClose={()=>setShowRoster(false)}/>}</>
  }
  return <Flow title="Roster check" step="4 OF 4" onBack={back}><div className={`validation-card ${validRoster(team)?'valid':'invalid'}`}>{validRoster(team)?<ShieldCheck/>:<X/>}<div><b>{validRoster(team)?'Your club is legal':'Roster needs attention'}</b><p>{team.roster.length}/20 players · {team.roster.filter(x=>x.role==='SP').length}/4 SP · {team.roster.filter(x=>x.role==='RP').length}/4 RP · {team.roster.filter(x=>x.role==='BAT').length}/12 BAT</p></div></div><div className="salary-meter"><span><b>{teamPayroll(team)}M</b> payroll</span><span>{CAP}M cap</span><i><em style={{width:`${teamPayroll(team)/CAP*100}%`}}/></i></div><p className="flow-copy">You may visit the market before continuing. Your roster must return to exactly 20 players.</p><button className="secondary wide" onClick={()=>setState(s=>({...s,phase:'hub',nav:'market'}))}><ArrowLeftRight/> Open market</button><button className="primary wide" disabled={!validRoster(team)} onClick={()=>setState(s=>{const x=structuredClone(s);x.league.teams=rollLeagueForm(x.league.teams);const fresh=x.league.teams[x.userId];x.phase='lineup';x.lineup=bestLineup(fresh);x.starterId=fresh.roster.filter(p=>p.role==='SP')[x.gameInSeries%4]?.id;return x})}>Set the Game {state.gameInSeries+1} lineup <ChevronRight/></button></Flow>
}

function makeTradeOffer(state){const us=state.league.teams[state.userId],others=state.league.teams.filter(t=>t.id!==state.userId);const other=others[Math.floor(Math.random()*others.length)];const ours=us.roster[Math.floor(Math.random()*us.roster.length)];const pool=other.roster.filter(p=>p.role===ours.role);const theirs=pool.sort((a,b)=>Math.abs(rating(a)-rating(ours))-Math.abs(rating(b)-rating(ours)))[0];return{teamId:other.id,ours:ours.id,theirs:theirs.id}}

function Lineup({state,setState,team,opponent,openPlayer}){
  const [dragIndex,setDragIndex]=useState(null),dragRef=useRef(null);
  const used=state.lineup.map(s=>s.playerId).filter(Boolean),usedStarters=state.usedStarters||[];const change=(idx,id)=>setState(s=>{const x=structuredClone(s);x.lineup[idx].playerId=id;return x});
  const moveSlot=(from,to)=>setState(s=>{if(from===to)return s;const x=structuredClone(s),[slot]=x.lineup.splice(from,1);x.lineup.splice(to,0,slot);return x});
  const beginDrag=(e,index)=>{e.preventDefault();dragRef.current=index;setDragIndex(index);e.currentTarget.setPointerCapture(e.pointerId)};
  const dragMove=e=>{if(dragRef.current==null)return;const row=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('[data-lineup-index]'),over=Number(row?.dataset.lineupIndex);if(Number.isInteger(over)&&over>=0&&over<state.lineup.length&&over!==dragRef.current){moveSlot(dragRef.current,over);dragRef.current=over;setDragIndex(over)}};
  const endDrag=e=>{if(dragRef.current==null)return;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}dragRef.current=null;setDragIndex(null)};
  const start=()=>setState(s=>{const x=structuredClone(s);x.usedStarters=[...(x.usedStarters||[]),x.starterId];const series=x.schedule[x.seriesIndex],arcade={ballparkId:x.ballparkId,boss:x.bossSeriesEnabled?(series.boss||null):null,bonds:x.bonds||[],artifacts:x.artifacts||{equipped:{}},cornerstoneId:x.cornerstoneId};x.game=makeGame(x.league.teams,x.userId,opponent.id,series.home,x.lineup,x.starterId,x.gameInSeries,x.philosophyId,arcade);x.phase='game';return x});
  const selectedStarter=team.roster.find(p=>p.id===state.starterId);
  return <Flow title={`Game ${state.gameInSeries+1} lineup`} step="SET THE ORDER" onBack={()=>setState(s=>({...s,phase:'prep-roster'}))} aside={<button className="text-btn orange" onClick={()=>setState(s=>({...s,lineup:bestLineup(team)}))}>Best lineup</button>}><div className="matchup-branding"><span><TeamMark team={team}/><b>{team.name}</b><small>YOU</small></span><i>VS</i><span><TeamMark team={opponent}/><b>{opponent.name}</b><small>{opponent.city}</small></span></div><div className="starter-pick"><small>STARTING PITCHER · USED STARTERS ARE LOCKED</small><div className="lineup-select-wrap">{selectedStarter&&<FormDot form={selectedStarter.form}/>}<select value={state.starterId||''} onChange={e=>setState(s=>({...s,starterId:e.target.value}))}>{team.roster.filter(p=>p.role==='SP').map(p=><option disabled={usedStarters.includes(p.id)} key={p.id} value={p.id}>{p.form==='hot'?'🔥 ':p.form==='cold'?'❄ ':''}{p.name} · {rating(p)} OVR{usedStarters.includes(p.id)?' · USED':''}</option>)}</select></div></div><div className="form-key"><span className="drag-tip"><GripVertical/> Drag to reorder</span><span><Flame/> Hot today</span><span><Snowflake/> Cold today</span></div><div className="lineup-list">{state.lineup.map((slot,i)=>{const selected=team.roster.find(p=>p.id===slot.playerId);return <div className={`lineup-slot ${selected?.form||''} ${dragIndex===i?'dragging':''}`} data-lineup-index={i} key={slot.playerId||i}><b>{i+1}</b><span>{slot.position}</span><FormDot form={selected?.form||'neutral'}/><select value={slot.playerId||''} onChange={e=>change(i,e.target.value)}>{team.roster.filter(p=>p.role==='BAT'&&(slot.position==='DH'||p.position===slot.position||p.secondary.includes(slot.position))&&(!used.includes(p.id)||p.id===slot.playerId)).map(p=><option key={p.id} value={p.id}>{p.form==='hot'?'🔥 ':p.form==='cold'?'❄ ':''}{p.name} · {rating(p)} · CON {p.contact} / POW {p.power} / EYE {p.eye}</option>)}</select><button className="player-peek" disabled={!slot.playerId} onClick={()=>openPlayer(slot.playerId)}><ChevronRight/></button><button className="drag-handle" aria-label={`Drag ${selected?.name||`spot ${i+1}`} to reorder`} onPointerDown={e=>beginDrag(e,i)} onPointerMove={dragMove} onPointerUp={endDrag} onPointerCancel={endDrag}><GripVertical/></button></div>})}</div><button className="primary wide" disabled={used.length!==9||new Set(used).size!==9||!state.starterId||usedStarters.includes(state.starterId)} onClick={start}><Play/> Play ball</button></Flow>
}

function StrikeZone({target,onTargetChange,showDot=true}){const move=e=>{const r=e.currentTarget.getBoundingClientRect();onTargetChange({x:clamp((e.clientX-r.left)/r.width*100,0,100),y:clamp((e.clientY-r.top)/r.height*100,0,100)})};return <div className="strike-zone-wrap" onPointerMove={e=>e.buttons&&move(e)} onPointerDown={e=>{e.currentTarget.setPointerCapture?.(e.pointerId);move(e)}}><div className="strike-zone"><i className="zone-corner tl"/><i className="zone-corner tr"/><i className="zone-corner bl"/><i className="zone-corner br"/><span className="zone-line"/>{showDot&&<b className="location-dot" style={{left:`${target.x}%`,top:`${target.y}%`}}/>}</div></div>}

function PitchControls({onPitch}){const [pitchType,setPitchType]=useState('fastball'),[target,setTarget]=useState({x:50,y:50}),[phase,setPhase]=useState('ready'),[meter,setMeter]=useState(0),started=useRef(0),power=useRef(0);useEffect(()=>{if(!['power','accuracy'].includes(phase))return;const id=setInterval(()=>{const elapsed=(performance.now()-started.current)/1100;const value=phase==='power'?Math.min(1,elapsed):Math.max(0,1-elapsed);setMeter(value);if(phase==='power'&&value>=1){power.current=1;started.current=performance.now();setPhase('accuracy')}},24);return()=>clearInterval(id)},[phase]);const tap=()=>{if(phase==='ready'){started.current=performance.now();setPhase('power');return}if(phase==='power'){power.current=meter;started.current=performance.now();setPhase('accuracy');return}const accuracy=1-Math.abs(meter-.25);onPitch({pitchType,target,action:Math.random()<.7?'swing':'take',power:power.current,accuracy});setPhase('ready');setMeter(0)};return <div className="play-controls pitcher-controls"><div className="control-label"><b>{phase==='ready'?'AIM YOUR PITCH':phase==='power'?'LOCK POWER': 'LOCK ACCURACY'}</b><span>{phase==='ready'?'Drag the dot, choose a pitch, then start the meter.':phase==='power'?'Tap near the top for maximum power.':'Tap at the orange line for accuracy.'}</span></div><StrikeZone target={target} onTargetChange={setTarget}/><div className="pitch-meter"><i style={{height:`${meter*100}%`}}/><span style={{bottom:'25%'}}/></div><div className="pitch-types">{[['fastball','Fastball'],['breaking','Breaking ball'],['changeup','Changeup']].map(([id,label])=><button className={pitchType===id?'active':''} key={id} onClick={()=>setPitchType(id)}>{label}</button>)}</div><button className="primary wide touch-action" onClick={tap}>{phase==='ready'?'Start pitch':phase==='power'?'Lock power':'Lock accuracy'}</button></div>}

function BatControls({onPitch}){const [ready,setReady]=useState(false),[target,setTarget]=useState({x:50,y:50}),start=useRef(0),moved=useRef(false);const begin=e=>{if(!ready)return;start.current=performance.now();moved.current=false;e.currentTarget.setPointerCapture?.(e.pointerId)};const move=e=>{if(!ready||moved.current)return;const dy=e.movementY||0;if(dy<-5)moved.current=true};const end=e=>{if(!ready||!moved.current)return;const elapsed=(performance.now()-start.current)/1000;const dx=e.clientX-(e.currentTarget.getBoundingClientRect().left+e.currentTarget.getBoundingClientRect().width/2);onPitch({action:'swing',target,timing:clamp(elapsed/.9,0,1),direction:dx<-35?'left':dx>35?'right':'center'});setReady(false)};return <div className="play-controls batting-controls"><div className="control-label"><b>{ready?'FLICK TO SWING':'READ THE PITCH'}</b><span>{ready?'Flick upward toward left, center, or right field.':'Tap Ready, then flick upward. Do nothing to take.'}</span></div><StrikeZone target={target} onTargetChange={setTarget}/>{ready&&<div className="timing-bar"><i/><b/></div>}<div className="flick-pad" onPointerDown={begin} onPointerMove={move} onPointerUp={end}><span>{ready?'FLICK UP':'SWING AREA'}</span></div><button className="primary wide touch-action" onClick={()=>setReady(true)} disabled={ready}>{ready?'Waiting for pitch':'Ready'}</button><button className="secondary wide" disabled={!ready} onClick={()=>{onPitch({action:'take',target});setReady(false)}}>Take pitch</button></div>}

function FieldPlay({result,onDone}){const [done,setDone]=useState(false);useEffect(()=>{const id=setTimeout(()=>setDone(true),1900);return()=>clearTimeout(id)},[]);return <div className={`field-play ${done?'complete':''}`} onClick={()=>setDone(true)}><div className="field-play-head"><small>IN PLAY · TAP TO FINISH</small><b>{result?.text||'Ball in play.'}</b></div><svg viewBox="0 0 320 220" role="img" aria-label="Animated field play"><path className="field-grass" d="M160 25 285 150 160 210 35 150Z"/><path className="field-dirt" d="M160 70 240 150 160 190 80 150Z"/><path className="field-path" d="M160 177 160 38"/><circle className="fielder" cx="160" cy="39" r="8"/><circle className="fielder" cx="75" cy="118" r="8"/><circle className="fielder" cx="245" cy="118" r="8"/><circle className="fielder" cx="160" cy="205" r="8"/><circle className="ball-flight" cx="160" cy="95" r="5"/></svg>{done&&<button className="primary wide" onClick={e=>{e.stopPropagation();onDone()}}>Next pitch</button>}</div>}

function Game({state,setState,openPlayer,toast}){
  const g=state.game,teams=state.league.teams,away=teams[g.awayId],home=teams[g.homeId],m=currentMatchup(g,teams),battingTeam=teams[m.offenseId],pitchingTeam=teams[m.defenseId],userBatting=m.offenseId===state.userId,userFielding=m.defenseId===state.userId,fatigue=fatigueState(m.pitcherState,m.pitcher),gamePark=BALLPARKS.find(p=>p.id===g.arcade?.ballparkId);
  const doStep=()=>setState(s=>({...s,game:stepPlateAppearance(s.game,s.league.teams)}));
  const skipHalf=()=>{const half=g.half,inn=g.inning;setState(s=>({...s,game:simulateUntil(s.game,s.league.teams,n=>n.half!==half||n.inning!==inn)}))};
  const skipGame=()=>setState(s=>({...s,game:simulateUntil(s.game,s.league.teams,n=>n.finished)}));
  const finish=()=>setState(s=>completeGame(s));
  const [sub,setSub]=useState(null),[field,setField]=useState(null);
  const playPitch=input=>{const next=resolvePitch(state.game,teams,input);setState(s=>({...s,game:next}));if(next.pitchResult?.kind==='in-play')setField(next.pitchResult)};
  const clearField=()=>setField(null);
  const count=g.count||{balls:0,strikes:0};
  return <div className="game-screen"><div className="game-head"><span>{g.inning}{g.half==='top'?'▲':'▼'}</span><div className="scoreline"><div className={away.id===state.userId?'your-team':''}><TeamMark team={away} size="tiny"/><b>{away.name.toUpperCase()}</b><strong>{g.score[away.id]}</strong><small>{g.hits[away.id]} H</small></div><div className={home.id===state.userId?'your-team':''}><TeamMark team={home} size="tiny"/><b>{home.name.toUpperCase()}</b><strong>{g.score[home.id]}</strong><small>{g.hits[home.id]} H</small></div></div><BaseDiamond bases={g.bases} outs={g.outs}/></div><div className="count-strip"><span>COUNT <b>{count.balls}-{count.strikes}</b></span><span>{g.outs} OUTS</span><span>{userBatting?'YOU BAT':'YOU PITCH'}</span></div>{(gamePark?.id!=='balanced'||g.arcade?.boss)&&<div className="arcade-game-ribbon"><span>{gamePark?.id!=='balanced'&&`${gamePark.icon} ${gamePark.name}`}</span><b>{g.arcade?.boss&&`BOSS: ${g.arcade.boss.name}`}</b></div>}
    {g.finished?<div className="final-panel"><span>FINAL</span><h2>{g.winnerId===state.userId?'That’s a winner.':'Not your night.'}</h2><div className="final-score"><b>{away.name} {g.score[away.id]}</b><b>{home.name} {g.score[home.id]}</b></div><button className="primary wide" onClick={finish}>Continue <ChevronRight/></button></div>:<>
      <div className="matchup"><button style={{'--club-primary':battingTeam.colors[0],'--club-secondary':battingTeam.colors[1]}} onClick={()=>openPlayer(m.batter.id)} className={`match-player ${m.batter.form}`}><div className="match-club"><TeamMark team={battingTeam} size="tiny"/><span><b>{battingTeam.name}</b><small>{battingTeam.id===state.userId?'YOUR TEAM':'OPPONENT'} · AT BAT · {m.batter.bats}HB</small></span></div><PlayerAvatar player={m.batter} size="large"/><b>{m.batter.name}</b><span>{m.batter.contact} CON · {m.batter.power} POW</span>{m.batter.form!=='neutral'&&<FormBadge form={m.batter.form}/>}</button><div className="versus">VS<small className={m.batter.bats===m.pitcher.throws?'pitch-edge':'bat-edge'}>{m.batter.bats===m.pitcher.throws?'PITCH EDGE':'BAT EDGE'}</small></div><button style={{'--club-primary':pitchingTeam.colors[0],'--club-secondary':pitchingTeam.colors[1]}} onClick={()=>openPlayer(m.pitcher.id)} className={`match-player ${m.pitcher.form}`}><div className="match-club"><TeamMark team={pitchingTeam} size="tiny"/><span><b>{pitchingTeam.name}</b><small>{pitchingTeam.id===state.userId?'YOUR TEAM':'OPPONENT'} · ON MOUND · {m.pitcher.throws}HP</small></span></div><PlayerAvatar player={m.pitcher} size="large"/><b>{m.pitcher.name}</b><span>{m.pitcher.velocity-fatigue.penalty} VEL · {m.pitcher.spin-fatigue.penalty} SPN</span><em className={`fatigue ${fatigue.tone}`}>{fatigue.name} · {m.pitcherState.bf} BF</em></button></div>
      <div className={`result-card ${g.lastResult?.kind||''}`}><small>LAST PLAY</small><p>{g.lastResult?.text||'The crowd settles in. Make your call.'}</p></div>
      {field?<FieldPlay result={field} onDone={clearField}/>:userFielding?<PitchControls onPitch={playPitch}/>:<BatControls onPitch={playPitch}/>}<div className="game-actions">{userFielding&&<button className="secondary" disabled={m.pitcher.role==='RP'&&m.pitcherState.bf<3} onClick={()=>setSub('pitcher')}><Users/> {m.pitcher.role==='RP'&&m.pitcherState.bf<3?`${3-m.pitcherState.bf} batters left`:'Change pitcher'}</button>}{userBatting&&<button className="secondary" onClick={()=>setSub('batter')}><Users/> Pinch hit</button>}<button className="secondary" onClick={doStep}><FastForward/> Sim batter</button><div className="skip-row"><button onClick={skipHalf}><FastForward/> Half inning</button><button onClick={skipGame}><FastForward/> Final</button></div></div>
      <div className="play-log">{g.log.slice(0,3).map(x=><p key={x.id}>{x.text}</p>)}</div>
    </>}
    {sub&&<SubSheet type={sub} state={state} matchup={m} onClose={()=>setSub(null)} onPick={id=>{setState(s=>({...s,game:sub==='pitcher'?substitutePitcher(s.game,s.userId,id):substituteBatter(s.game,s.userId,m.batter.id,id)}));setSub(null);toast(sub==='pitcher'?'Bullpen change made.':'Pinch hitter announced.')}}/>}
  </div>
}

function completeGame(s){
  const x=structuredClone(s),g=x.game,series=x.schedule[x.seriesIndex],user=x.league.teams[x.userId],opp=x.league.teams[series.opponentId],won=g.winnerId===x.userId,ur=g.score[x.userId],or=g.score[opp.id];
  user.wins+=won?1:0;user.losses+=won?0:1;opp.wins+=won?0:1;opp.losses+=won?1:0;user.runsFor+=ur;user.runsAgainst+=or;opp.runsFor+=or;opp.runsAgainst+=ur;
  Object.entries(g.stats).forEach(([id,st])=>{const pl=[...user.roster,...opp.roster].find(p=>p.id===id);if(pl){pl.stats={...statOf(pl)};Object.keys(st).forEach(k=>{pl.stats[k]=(pl.stats[k]||0)+st[k]});pl.stats.g++}});
  x.news.unshift(`${won?'Won':'Lost'} ${ur}–${or} against the ${opp.name}.`);if(opp.id===user.rivalId){x.rivalRecord[won?'wins':'losses']++}
  // Keep the wider league moving one game at a time.
  const others=x.league.teams.filter(t=>t.id!==user.id&&t.id!==opp.id).sort(()=>Math.random()-.5);for(let i=0;i<others.length;i+=2){const a=others[i],b=others[i+1];if(!b)continue;const [ar,br]=quickGame(a,b);a.wins+=ar>br?1:0;a.losses+=ar<br?1:0;b.wins+=br>ar?1:0;b.losses+=br<ar?1:0;a.runsFor+=ar;a.runsAgainst+=br;b.runsFor+=br;b.runsAgainst+=ar;applyQuickStats(a,ar,br);applyQuickStats(b,br,ar)}
  series.played++;series.userWins=(series.userWins||0)+(won?1:0);x.gameInSeries++;x.game=null;
  if(x.gameInSeries>=4){
    if(x.bossSeriesEnabled&&series.boss&&series.userWins>=3){const reward=series.boss.reward;x.artifacts??={inventory:[],equipped:{}};if(!x.artifacts.inventory.includes(reward)){x.artifacts.inventory.push(reward);x.news.unshift(`Boss defeated: ${series.boss.name}. You stole the ${artifactById(reward)?.name}.`);x.legacy+=5}}
    x.seriesIndex++;x.gameInSeries=0;x.usedStarters=[];x.prep=null;if(x.seriesIndex>=8){x.phase='season-end'}else{x.phase='hub';x.nav='home'}
  }else{x.league.teams=rollLeagueForm(x.league.teams);const fresh=x.league.teams[x.userId];x.phase='lineup';x.lineup=bestLineup(fresh);x.starterId=fresh.roster.filter(p=>p.role==='SP'&&!(x.usedStarters||[]).includes(p.id))[0]?.id}
  return x;
}

function SeasonEnd({state,setState}){
  const user=state.league.teams[state.userId],ranked=[...state.league.teams.filter(t=>t.league===user.league)].sort((a,b)=>b.wins-a.wins||a.losses-b.losses),seed=ranked.findIndex(t=>t.id===user.id)+1,qualified=seed<=2;const [ran,setRan]=useState(state.postseason);
  const play=()=>{const leagueOpp=ranked.find(t=>t.id!==user.id);let leagueWin=false,title=false;if(qualified){const strength=ratingAvg(user)-ratingAvg(leagueOpp);leagueWin=Math.random()<clamp(.5+strength*.025,.2,.8);if(leagueWin)title=Math.random()<clamp(.48+strength*.018,.22,.78)}const result={qualified,leagueWin,title,seed};setRan(result);setState(s=>({...s,postseason:result}));};
  const offseason=()=>setState(s=>beginOffseason(s));
  return <Flow title="The postseason" step={`YEAR ${state.year}`}><div className="season-record"><small>REGULAR SEASON</small><b>{user.wins}–{user.losses}</b><span>#{seed} in {user.league}</span></div>{!ran?<><p className="flow-copy">{qualified?`You’re in. The #${seed} seed meets the ${leagueOppName(ranked,user)} in a best-of-five league championship.`:'The top two moved on without you. The postseason will play out before the offseason begins.'}</p><button className="primary wide" onClick={play}><Trophy/> Play postseason</button></>:<><div className={`postseason-result ${ran.title?'champion':''}`}><Award/><h2>{ran.title?'World champions!':ran.leagueWin?'League champions':'Season over'}</h2><p>{ran.title?'You climbed through two best-of-five series and won the whole ridiculous thing.':ran.leagueWin?'The league pennant is yours, but the championship slipped away.':ran.qualified?'The league championship ended your run.':'Watch October from the couch and start plotting.'}</p></div><button className="primary wide" onClick={offseason}>Begin offseason <ChevronRight/></button></>}</Flow>
}
const ratingAvg=t=>t.roster.reduce((s,p)=>s+rating(p),0)/t.roster.length;const leagueOppName=(ranked,user)=>fullTeamName(ranked.find(t=>t.id!==user.id));

function beginOffseason(s){const x=structuredClone(s),team=x.league.teams[x.userId],notes=[];if(x.postseason?.qualified){team.history.playoffs++;x.legacy+=8}if(x.postseason?.leagueWin)x.legacy+=15;if(x.postseason?.title){team.history.championships++;x.legacy+=40;team.roster.forEach(p=>p.championships++)}
  const leaving=[];team.roster.forEach(p=>{p.age++;p.careerSeasons++;const retire=p.age>=36&&Math.random()<.12+(p.age-36)*.1;const depart=Math.random()<clamp(.02+Math.max(0,p.tenure-1)*.045+(x.philosophyId==='youth'&&p.age>29?.05:0),0,.42);if(retire||depart)leaving.push({p,reason:retire?'retired':'left for free agency'});else p.tenure++});
  team.roster=team.roster.filter(p=>!leaving.some(l=>l.p.id===p.id));leaving.forEach(l=>{notes.push(`${l.p.name} ${l.reason}.`);delete x.artifacts?.equipped?.[l.p.id];if(x.cornerstoneId===l.p.id)x.cornerstoneId=null;if(l.reason!=='retired'){l.p.teamId=null;l.p.tenure=0;x.league.freeAgents.push(l.p)}});x.bonds=(x.bonds||[]).filter(d=>d.players.every(id=>team.roster.some(p=>p.id===id)));x.news.unshift(...notes);x.offseason={leaving:notes,prospects:Array.from({length:8},(_,i)=>makePlayer(i<2?'SP':i<3?'RP':'BAT',i<3?undefined:POSITIONS[(i-3)%POSITIONS.length],null,true)),drafted:false,labUsed:false};x.phase='offseason-summary';return x}

function Offseason({state,setState,openPlayer,toast}){
  const [draftSort,setDraftSort]=useState('position'),[showRoster,setShowRoster]=useState(false),[labPlayerId,setLabPlayerId]=useState(null);
  const team=state.league.teams[state.userId],o=state.offseason;
  if(state.phase==='offseason-summary')return <Flow title="Winter arrives" step="RETIREMENTS & DEPARTURES"><div className="season-record"><small>PLAYERS REMAINING</small><b>{team.roster.length}</b><span>{20-team.roster.length} openings</span></div><div className="event-list">{o.leaving.length?o.leaving.map((n,i)=><p key={i}><History/>{n}</p>):<p><ShieldCheck/>Everybody is coming back.</p>}</div><button className="primary wide" onClick={()=>setState(s=>({...s,phase:'offseason-draft'}))}>Go to the draft <ChevronRight/></button></Flow>;
  if(state.phase==='offseason-draft'){
    const prospects=[...o.prospects].sort((a,b)=>draftSort==='current'?rating(b)-rating(a)||byPosition(a,b):draftSort==='potential'?potential(b)-potential(a)||rating(b)-rating(a):byPosition(a,b));
    return <><Flow title="The rookie draft" step={`PICK ${20-team.wins} · ONE ROUND`} aside={<button className="text-btn roster-peek" onClick={()=>setShowRoster(true)}><Users/> My roster</button>}><p className="flow-copy">Potential is a scouting range, not an exact promise. Wild-card prospects have extreme strengths and very real flaws.</p><div className="draft-sort" aria-label="Sort draft prospects"><button className={draftSort==='position'?'active':''} onClick={()=>setDraftSort('position')}>Position</button><button className={draftSort==='current'?'active':''} onClick={()=>setDraftSort('current')}>Current</button><button className={draftSort==='potential'?'active':''} onClick={()=>setDraftSort('potential')}>Potential</button></div><div className="prospect-list">{prospects.map(p=><div className={`prospect-row ${p.wildCard?'wild':''}`} key={p.id}><button className="prospect-open" onClick={()=>openPlayer(p.id)}><PlayerAvatar player={p} size="small"/><span><b>{p.name}</b><small>{p.position} · Age {p.age} · {p.salary}M</small>{p.wildCard&&<i>{p.wildCard.name}</i>}</span><em>{rating(p)} <small>CURRENT</small></em><em>{potentialRange(p)} <small>POTENTIAL</small></em></button><button className="draft-btn" onClick={()=>setState(s=>{const x=structuredClone(s),pick=x.offseason.prospects.find(z=>z.id===p.id),t=x.league.teams[x.userId];pick.teamId=t.id;pick.originTeamId=t.id;pick.draftedYear=x.year;pick.draftPick=20-t.wins;t.roster.push(pick);x.offseason.drafted=true;x.news.unshift(`Drafted ${pick.name}, a ${pick.position}, in round one.`);x.phase='offseason-lab';return x})}>DRAFT</button></div>)}</div></Flow>{showRoster&&<RosterOverlay team={team} onClose={()=>setShowRoster(false)}/>}</>;
  }
  if(state.phase==='offseason-lab'){
    const selected=team.roster.find(p=>p.id===(labPlayerId||team.roster[0]?.id));
    const experiment=kind=>setState(s=>{const x=structuredClone(s),t=x.league.teams[x.userId],pl=t.roster.find(p=>p.id===(labPlayerId||t.roster[0]?.id));if(!pl)return x;const traits=pl.role==='BAT'?BAT_TRAITS:PITCH_TRAITS;if(kind==='youth'){pl.age=Math.max(19,pl.age-3);x.news.unshift(`The lab made ${pl.name} three years younger. Nobody asks how.`)}if(kind==='ceiling'){traits.forEach(k=>pl[`${k}Pot`]=Math.min(99,pl[`${k}Pot`]+8));x.news.unshift(`${pl.name}'s potential ceiling surged in the lab.`)}if(kind==='overclock'){const best=[...traits].sort((a,b)=>pl[b]-pl[a])[0],worst=[...traits].sort((a,b)=>pl[a]-pl[b])[0];pl[best]=Math.min(pl[`${best}Pot`],pl[best]+10);pl[worst]=Math.max(20,pl[worst]-7);x.news.unshift(`${pl.name} was overclocked: more ${best}, less ${worst}.`)}if(kind==='mutation'&&pl.role==='BAT'){const pos=POSITIONS.find(pos=>pos!==pl.position&&!pl.secondary.includes(pos));if(pos)pl.secondary.push(pos);pl.speed=Math.min(pl.speedPot,pl.speed+5);x.news.unshift(`${pl.name} emerged able to play ${pos||pl.position}.`)}pl.labMark=kind;x.offseason.labUsed=true;x.phase='offseason-roster';return x});
    return <Flow title="The baseball laboratory" step="ONE EXPERIMENT · NO REFUNDS"><p className="flow-copy">Choose one player, then perform one dangerous experiment. Results are permanent.</p><select className="lab-player-select" value={selected?.id||''} onChange={e=>setLabPlayerId(e.target.value)}>{[...team.roster].sort(byPosition).map(p=><option key={p.id} value={p.id}>{p.position} · {p.name} · {rating(p)} OVR</option>)}</select><div className="lab-subject">{selected&&<><PlayerAvatar player={selected} size="medium"/><span><small>TEST SUBJECT</small><b>{selected.name}</b><p>{selected.position} · Age {selected.age} · {rating(selected)} OVR</p></span></>}</div><div className="lab-grid"><button onClick={()=>experiment('youth')}><b>AGE REVERSAL</b><span>Become three years younger.</span></button><button onClick={()=>experiment('ceiling')}><b>POTENTIAL STORM</b><span>+8 to every potential trait.</span></button><button onClick={()=>experiment('overclock')}><b>OVERCLOCK</b><span>Supercharge the best trait; damage the worst.</span></button><button disabled={selected?.role!=='BAT'} onClick={()=>experiment('mutation')}><b>POSITION MUTATION</b><span>Learn a position and gain speed.</span></button></div></Flow>
  }
  const finish=()=>{if(!validRoster(team)){toast('A legal 20-player roster is required.');return}setState(s=>{const x=structuredClone(s);x.year++;x.league.teams.forEach(t=>{t.wins=0;t.losses=0;t.runsFor=0;t.runsAgainst=0});x.schedule=scheduleFor(x.userId,x.league.teams);x.seriesIndex=0;x.gameInSeries=0;x.phase='hub';x.nav='home';x.prep=null;x.postseason=null;x.offseason=null;const t=x.league.teams[x.userId];x.bonds=(x.bonds||[]).filter(d=>d.players.every(id=>t.roster.some(p=>p.id===id)));if(!x.bonds.length){const duo=createDuo(t);if(duo)x.bonds=[duo]}x.news.unshift(`Year ${x.year} begins. A clean slate and 32 games ahead.`);return x})};
  return <Flow title="Build the 20" step="ROSTER DECISIONS"><div className={`validation-card ${validRoster(team)?'valid':'invalid'}`}>{validRoster(team)?<ShieldCheck/>:<Users/>}<div><b>{team.roster.length}/20 players · {teamPayroll(team)}/{CAP}M</b><p>{team.roster.filter(x=>x.role==='SP').length}/4 SP · {team.roster.filter(x=>x.role==='RP').length}/4 RP · {team.roster.filter(x=>x.role==='BAT').length}/12 BAT</p></div></div><Roster team={team} openPlayer={openPlayer} compact onRelease={id=>setState(s=>releasePlayer(s,id))}/><h3 className="subhead">Immediate free agents</h3><FreeAgentList state={state} setState={setState} openPlayer={openPlayer} toast={toast}/><button className="primary wide sticky-action" disabled={!validRoster(team)} onClick={finish}>Start Year {state.year+1} <ChevronRight/></button></Flow>
}

function Roster({team,openPlayer,compact=false,onRelease}){const groups=[['STARTING ROTATION',[...team.roster.filter(p=>p.role==='SP')].sort((a,b)=>rating(b)-rating(a))],['BULLPEN',[...team.roster.filter(p=>p.role==='RP')].sort((a,b)=>rating(b)-rating(a))],['POSITION PLAYERS',[...team.roster.filter(p=>p.role==='BAT')].sort(byPosition)]];return <div className={compact?'roster compact':'page roster'}>{!compact&&<PageHead kicker="THE TWENTY" title="Active roster" meta={`${teamPayroll(team)}/${CAP}M`}/>} {groups.map(([label,players])=><section key={label}><SectionTitle label={label}/><div className="player-table">{players.map(p=><button key={p.id} onClick={()=>openPlayer(p.id)}><FormDot form={p.form}/><span className="player-pos">{positionsLabel(p)}</span><span className="player-name"><b>{p.name}</b><small>{p.bats}HB · Age {p.age}</small></span><span className="rating"><b>{rating(p)}</b><small>{potential(p)} POT</small></span><span className="salary">{p.salary}M</span>{onRelease&&<button className="release" onClick={e=>{e.stopPropagation();onRelease(p.id)}}><X/></button>}<ChevronRight/></button>)}</div></section>)}</div>}

function League({state,openPlayer}){
  const [tab,setTab]=useState('standings'),user=state.league.teams[state.userId],players=state.league.teams.flatMap(t=>t.roster.map(p=>({...p,club:t})));
  return <div className="page"><PageHead kicker={`YEAR ${state.year}`} title="League center" meta="32 GAMES"/><div className="segmented stats-tabs"><button className={tab==='standings'?'active':''} onClick={()=>setTab('standings')}>Standings</button><button className={tab==='batters'?'active':''} onClick={()=>setTab('batters')}>Batters</button><button className={tab==='pitchers'?'active':''} onClick={()=>setTab('pitchers')}>Pitchers</button><button className={tab==='teams'?'active':''} onClick={()=>setTab('teams')}>Teams</button></div>
    {tab==='standings'&&['Circuit A','Circuit B'].map(l=><section key={l}><SectionTitle label={l}/><div className="standings"><div className="stand-row labels"><span>RK</span><span>CLUB</span><span>W</span><span>L</span><span>DIFF</span></div>{[...state.league.teams.filter(t=>t.league===l)].sort((a,b)=>b.wins-a.wins||a.losses-b.losses).map((t,i)=><div className={`stand-row ${t.id===user.id?'you':''}`} key={t.id}><span>{i+1}</span><span><TeamMark team={t} size="tiny"/>{t.city} {t.name}{t.id===user.rivalId&&<Swords/>}</span><b>{t.wins}</b><span>{t.losses}</span><span className={t.runsFor-t.runsAgainst>=0?'pos':'neg'}>{t.runsFor-t.runsAgainst>0?'+':''}{t.runsFor-t.runsAgainst}</span></div>)}</div></section>)}
    {tab==='batters'&&<PlayerStatTable type="batters" players={players.filter(p=>p.role==='BAT')} onOpen={openPlayer}/>} 
    {tab==='pitchers'&&<PlayerStatTable type="pitchers" players={players.filter(p=>p.role!=='BAT')} onOpen={openPlayer}/>} 
    {tab==='teams'&&<TeamStatTable teams={state.league.teams}/>} 
  </div>
}

function PlayerStatTable({type,players,onOpen}){
  const sorted=[...players].sort((a,b)=>type==='batters'?Number(playerOps(b).replace('---','0'))-Number(playerOps(a).replace('---','0')):Number(playerEra(a).replace('—','999'))-Number(playerEra(b).replace('—','999')));
  return <><p className="stats-note">Season totals update after every game. Tap a player for their full card.</p><div className="stat-table-wrap"><div className={`stat-table ${type}`}><div className="stat-row head"><span>PLAYER</span>{type==='batters'?<><b>PA</b><b>AVG</b><b>HR</b><b>OPS</b></>:<><b>IP</b><b>K</b><b>WHIP</b><b>ERA</b></>}</div>{sorted.map(p=><button className="stat-row" key={p.id} onClick={()=>onOpen(p.id)}><span><i className="swatch" style={{background:p.club.colors[0]}}/><em>{p.name}<small>{p.club.city.slice(0,3).toUpperCase()} · {p.position}</small></em></span>{type==='batters'?<><b>{statOf(p).pa}</b><b>{battingAvg(p)}</b><b>{statOf(p).hr}</b><b className="accent-stat">{playerOps(p)}</b></>:<><b>{innings(p)}</b><b>{statOf(p).k}</b><b>{playerWhip(p)}</b><b className="accent-stat">{playerEra(p)}</b></>}</button>)}</div></div></>
}

function TeamStatTable({teams}){
  return <><p className="stats-note">Complete club batting, pitching, and scoring totals.</p><div className="team-stats">{teams.map(t=>{const s=teamStatLine(t);return <div className="team-stat-card" key={t.id}><header><TeamMark team={t}/><b>{fullTeamName(t)}</b><span>{t.wins}–{t.losses}</span></header><div><span><small>AVG</small><b>{s.avg}</b></span><span><small>HR</small><b>{s.hr}</b></span><span><small>OPS</small><b>{s.ops}</b></span><span><small>K</small><b>{s.k}</b></span><span><small>WHIP</small><b>{s.whip}</b></span><span><small>ERA</small><b>{s.era}</b></span><span><small>RUNS FOR</small><b>{t.runsFor}</b></span><span><small>RUNS AGAINST</small><b>{t.runsAgainst}</b></span></div></div>})}</div></>
}

function Market({state,setState,openPlayer,toast}){
  const team=state.league.teams[state.userId],firstOther=state.league.teams.find(t=>t.id!==team.id);
  const [tab,setTab]=useState('agents'),[ours,setOurs]=useState(null),[theirs,setTheirs]=useState(null),[otherId,setOtherId]=useState(firstOther.id),[side,setSide]=useState('theirs'),[feedback,setFeedback]=useState('');
  const other=state.league.teams.find(t=>t.id===Number(otherId))||firstOther,ourPick=team.roster.find(p=>p.id===ours),theirPick=other.roster.find(p=>p.id===theirs);
  const evaluation=evaluateTrade(ourPick,theirPick,other);
  const chooseTeam=id=>{setOtherId(Number(id));setTheirs(null);setFeedback('');setSide('theirs')};
  const trade=()=>{if(!ourPick||!theirPick||!evaluation)return;if(teamPayroll(team)-ourPick.salary+theirPick.salary>CAP){setFeedback('Your club cannot fit this trade under the cap.');return}if(!evaluation.accepted){setFeedback(`${other.city} declined. Your offer scored ${evaluation.offered.toFixed(1)} against their ${evaluation.asked.toFixed(1)} valuation.`);return}setState(s=>{const x=structuredClone(s),ut=x.league.teams[x.userId],ot=x.league.teams.find(t=>t.id===other.id),pa=ut.roster.find(p=>p.id===ours),pb=ot.roster.find(p=>p.id===theirs);ut.roster=ut.roster.filter(p=>p.id!==pa.id);ot.roster=ot.roster.filter(p=>p.id!==pb.id);pa.teamId=ot.id;pb.teamId=ut.id;ut.roster.push(pb);ot.roster.push(pa);x.news.unshift(`You traded ${pa.name} to ${ot.city} for ${pb.name}.`);return x});setOurs(null);setTheirs(null);setFeedback('');setSide('ours');toast(`${other.city} accepted the trade.`);};
  const shown=side==='ours'?team:other,selected=side==='ours'?ours:theirs,setSelected=side==='ours'?setOurs:setTheirs;
  return <div className="page"><PageHead kicker="DEAL DESK" title="Player market" meta={`${CAP-teamPayroll(team)}M SPACE`}/><div className="segmented"><button className={tab==='agents'?'active':''} onClick={()=>setTab('agents')}>Free agents</button><button className={tab==='trade'?'active':''} onClick={()=>setTab('trade')}>Propose trade</button></div>{tab==='agents'?<FreeAgentList state={state} setState={setState} openPlayer={openPlayer} toast={toast}/>:<div className="trade-center">
    <label className="team-picker"><small>TRADE WITH</small><select value={other.id} onChange={e=>chooseTeam(e.target.value)}>{state.league.teams.filter(t=>t.id!==team.id).map(t=><option key={t.id} value={t.id}>{fullTeamName(t)} · {t.wins}–{t.losses}</option>)}</select></label>
    <div className="trade-summary"><TradePick label="YOU SEND" player={ourPick}/><ArrowLeftRight/><TradePick label="YOU RECEIVE" player={theirPick}/></div>
    <div className="trade-roster-tabs"><button className={side==='ours'?'active':''} onClick={()=>setSide('ours')}>Your roster {ours&&'✓'}</button><button className={side==='theirs'?'active':''} onClick={()=>setSide('theirs')}>{other.city} roster {theirs&&'✓'}</button></div>
    {evaluation&&<TradeEvaluation evaluation={evaluation} other={other}/>} 
    {feedback&&<div className="trade-feedback"><X/>{feedback}</div>}
    <div className="trade-roster-list"><div className="trade-list-head"><span>{fullTeamName(shown)}</span><small>TAP A PLAYER TO SELECT</small></div>{shown.roster.map(p=><button className={selected===p.id?'selected':''} key={p.id} onClick={()=>{setSelected(p.id);setFeedback('');if(side==='ours')setSide('theirs')}}><PlayerAvatar player={p} size="tiny"/><span><b>{p.name}</b><small>{p.position} · Age {p.age} · {p.salary}M</small></span><em>{rating(p)}<small>OVR</small></em><em>{potential(p)}<small>POT</small></em><FormDot form={p.form}/></button>)}</div>
    <button className="primary wide" disabled={!ourPick||!theirPick||!evaluation?.roleOk} onClick={trade}>Send offer to {other.city}</button><p className="fineprint">The other club weighs current ability, potential, age, salary, roster fit, and its own salary cap.</p>
  </div>}</div>
}

function TradePick({label,player}){return <div className={`trade-pick ${player?'filled':''}`}><small>{label}</small>{player?<><PlayerAvatar player={player} size="small"/><b>{player.name}</b><span>{player.position} · {rating(player)} OVR · {player.salary}M</span></>:<><span className="pick-empty">?</span><b>Choose player</b></>}</div>}
function TradeEvaluation({evaluation,other}){return <div className={`trade-evaluation ${evaluation.accepted?'accept':'decline'}`}><header><span><small>{other.city.toUpperCase()} FRONT OFFICE</small><b>{evaluation.label}</b></span><em>{evaluation.offered.toFixed(1)}<small>OFFER</small></em><i>/</i><em>{evaluation.asked.toFixed(1)}<small>ASK</small></em></header><div className="value-track"><i style={{width:`${clamp(evaluation.offered/(Math.max(evaluation.offered,evaluation.asked)*1.12)*100,8,100)}%`}}/></div><ul>{evaluation.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul></div>}

function FreeAgentList({state,setState,openPlayer,toast}){
  const team=state.league.teams[state.userId],[pending,setPending]=useState(null),limits={SP:4,RP:4,BAT:12};
  const sign=p=>{const rosterFull=team.roster.length>=20,roleFull=team.roster.filter(x=>x.role===p.role).length>=limits[p.role];if(rosterFull||roleFull){setPending(p);return}if(teamPayroll(team)+p.salary>CAP){toast('Not enough cap space.');return}setState(s=>completeSigning(s,p.id));toast(`${p.name} signed immediately.`)};
  const replace=id=>{const released=team.roster.find(p=>p.id===id);setState(s=>completeSigning(s,pending.id,id));toast(`${pending.name} signed. ${released.name} was released.`);setPending(null)};
  return <><div className="fa-list">{state.league.freeAgents.slice(0,24).map(p=><button key={p.id} onClick={()=>openPlayer(p.id)}><span className="player-pos">{p.position}</span><span><b>{p.name}</b><small>{rating(p)} OVR · {potential(p)} POT · Age {p.age}</small></span><em>{p.salary}M</em><button className="sign" onClick={e=>{e.stopPropagation();sign(p)}}><Plus/> SIGN</button></button>)}</div>{pending&&<SigningSheet freeAgent={pending} team={team} onClose={()=>setPending(null)} onPick={replace}/>}</>
}

function completeSigning(s,freeAgentId,releaseId=null){
  const x=structuredClone(s),team=x.league.teams[x.userId],fa=x.league.freeAgents.find(p=>p.id===freeAgentId);if(!fa)return x;
  if(releaseId){const released=team.roster.find(p=>p.id===releaseId);team.roster=team.roster.filter(p=>p.id!==releaseId);released.teamId=null;released.tenure=0;x.league.freeAgents.push(released)}
  fa.teamId=team.id;fa.tenure=1;team.roster.push(fa);x.league.freeAgents=x.league.freeAgents.filter(p=>p.id!==freeAgentId);x.news.unshift(`${fa.name} signed for ${fa.salary}M${releaseId?' as a roster replacement':''}.`);return x;
}

function SigningSheet({freeAgent,team,onClose,onPick}){
  const [sortBy,setSortBy]=useState('position');
  const limits={SP:4,RP:4,BAT:12},current={SP:team.roster.filter(p=>p.role==='SP').length,RP:team.roster.filter(p=>p.role==='RP').length,BAT:team.roster.filter(p=>p.role==='BAT').length};
  const eligible=team.roster.filter(candidate=>{const next={...current};next[candidate.role]--;next[freeAgent.role]++;return next.SP<=limits.SP&&next.RP<=limits.RP&&next.BAT<=limits.BAT}).sort((a,b)=>sortBy==='overall'?rating(b)-rating(a)||byPosition(a,b):sortBy==='age'?b.age-a.age||byPosition(a,b):byPosition(a,b));
  return <div className="sheet-wrap" onClick={onClose}><div className="sheet signing-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={onClose}><X/></button><div className="signing-title"><PlayerAvatar player={freeAgent} size="medium"/><div><small>MAKE ROOM FOR</small><h2>{freeAgent.name}</h2><p>{freeAgent.position} · Age {freeAgent.age} · {rating(freeAgent)} OVR · {freeAgent.salary}M</p></div></div><div className="swap-payroll"><span>Current payroll <b>{teamPayroll(team)}M</b></span><span>Salary cap <b>{CAP}M</b></span></div><p className="flow-copy">Choose the player to release. Only swaps that preserve legal roster-role counts are shown.</p><div className="release-sort" aria-label="Sort release candidates"><small>SORT ROSTER</small>{[['position','Position'],['overall','Overall'],['age','Age']].map(([id,label])=><button key={id} className={sortBy===id?'active':''} aria-pressed={sortBy===id} onClick={()=>setSortBy(id)}>{label}</button>)}</div><div className="release-options">{eligible.map(p=>{const next=teamPayroll(team)-p.salary+freeAgent.salary,canAfford=next<=CAP;return <button disabled={!canAfford} key={p.id} onClick={()=>onPick(p.id)}><PlayerAvatar player={p} size="tiny"/><span><b>Release {p.name}</b><small>{positionsLabel(p)} · Age {p.age} · {rating(p)} OVR · {p.salary}M</small></span><em className={canAfford?'pos':'neg'}>{next}M<small>{canAfford?'NEW PAYROLL':'OVER CAP'}</small></em><ChevronRight/></button>})}</div>{!eligible.length&&<div className="trade-feedback"><X/>No single release can create a legal roster for this signing.</div>}</div></div>
}

function releasePlayer(s,id){const x=structuredClone(s),t=x.league.teams[x.userId],p=t.roster.find(z=>z.id===id);if(!p)return x;t.roster=t.roster.filter(z=>z.id!==id);p.teamId=null;p.tenure=0;x.league.freeAgents.push(p);return x}

function Club({state,setState}){
  const [picker,setPicker]=useState(null);
  const team=state.league.teams[state.userId],phil=philosophies.find(p=>p.id===state.philosophyId),cornerstone=team.roster.find(p=>p.id===state.cornerstoneId),park=BALLPARKS.find(p=>p.id===state.ballparkId)||BALLPARKS[0];
  const equip=(artifactId,playerId)=>setState(s=>{const x=structuredClone(s);x.artifacts??={inventory:[],equipped:{}};Object.keys(x.artifacts.equipped).forEach(id=>{if(x.artifacts.equipped[id]===artifactId||id===playerId)delete x.artifacts.equipped[id]});if(playerId)x.artifacts.equipped[playerId]=artifactId;return x});
  const chooseCornerstone=id=>{setState(s=>({...s,cornerstoneId:id,cornerstoneYear:s.year}));setPicker(null)};
  const chooseArtifact=(artifactId,id)=>{equip(artifactId,id);setPicker(null)};
  const choosePhilosophy=id=>{setState(s=>({...s,philosophyId:id,news:[`${philosophies.find(p=>p.id===id).name} is now the club philosophy.`,...s.news]}));setPicker(null)};
  const owned=state.artifacts?.inventory||[];
  return <><div className="page"><PageHead kicker="THE OWNER'S BOX" title="Club identity" meta={`LEGACY ${state.legacy}`}/><div className="legacy-card"><Award/><div><small>OWNER LEGACY</small><b>{state.legacy}</b><p>Built from wins, pennants, titles and time.</p></div></div><div className="history-grid"><div><b>{team.history.championships}</b><span>Championships</span></div><div><b>{team.history.playoffs}</b><span>Playoff trips</span></div><div><b>{state.rivalRecord.wins}–{state.rivalRecord.losses}</b><span>Rivalry record</span></div><div><b>{state.year}</b><span>Seasons owned</span></div></div>
    <SectionTitle label="Home ballpark"/><div className="identity-feature"><i>{park.icon}</i><span><b>{park.name}</b><small>{park.effect}</small></span></div><div className="park-grid">{BALLPARKS.map(p=><button className={p.id===state.ballparkId?'active':''} key={p.id} onClick={()=>setState(s=>({...s,ballparkId:p.id}))}><i>{p.icon}</i><b>{p.name}</b><span>{p.note}</span></button>)}</div>
    <SectionTitle label="Franchise cornerstone"/><div className="cornerstone-card">{cornerstone?<><PlayerAvatar player={cornerstone} size="medium"/><span><small>THE FACE OF THE FRANCHISE</small><b>{cornerstone.name}</b><p>{positionsLabel(cornerstone)} · {rating(cornerstone)} OVR · +2 to every game skill.</p></span></>:<><UserRound/><span><b>No cornerstone chosen</b><p>Choose one player for this season.</p></span></>}<button className="manage-btn" disabled={state.cornerstoneYear===state.year} onClick={()=>setPicker({type:'cornerstone'})}>{state.cornerstoneYear===state.year?'Locked for this season':cornerstone?'Choose new cornerstone':'Choose cornerstone'}<ChevronRight/></button></div>
    <SectionTitle label="Artifact vault"/><div className="vault-guide"><Sparkles/><span><b>How artifacts work</b><p>You begin with two. Win at least 3 games in a Boss Series to steal its featured artifact. One player may equip one artifact, and equipment can move at any time.</p></span></div><div className="artifact-vault">{ARTIFACTS.map(a=>{const isOwned=owned.includes(a.id),holderId=Object.keys(state.artifacts?.equipped||{}).find(pid=>state.artifacts.equipped[pid]===a.id),holder=team.roster.find(p=>p.id===holderId);return <div className={isOwned?'':'locked'} key={a.id}><i>{isOwned?a.icon:'?'}</i><span><b>{a.name}</b><small>{a.note}</small>{isOwned&&<em>{holder?`EQUIPPED: ${holder.name}`:'UNEQUIPPED'}</em>}</span>{isOwned?<button className="manage-btn" onClick={()=>setPicker({type:'artifact',artifactId:a.id})}>{holder?'Move':'Equip'}<ChevronRight/></button>:<strong>WIN ITS BOSS SERIES</strong>}</div>})}</div>
    {state.bonds?.[0]&&<DuoCard duo={state.bonds[0]} team={team}/>}<SectionTitle label="Club philosophy"/><div className="philosophy-card interactive"><i>{phil.icon}</i><div><b>{phil.name}</b><p>{phil.benefit} {phil.drawback}</p><small>Changes affect future development and games.</small></div><button className="manage-btn" onClick={()=>setPicker({type:'philosophy'})}>Change<ChevronRight/></button></div><SectionTitle label="Game options"/><button className={`option-toggle ${state.bossSeriesEnabled?'on':'off'}`} role="switch" aria-checked={state.bossSeriesEnabled} onClick={()=>setState(s=>({...s,bossSeriesEnabled:!s.bossSeriesEnabled}))}><span><Swords/><i><b>Boss Series</b><small>{state.bossSeriesEnabled?'Special opponents, modifiers, and artifact rewards are active.':'All series play with normal rules and no boss rewards.'}</small></i></span><em><strong>{state.bossSeriesEnabled?'ON':'OFF'}</strong><i/></em></button><SectionTitle label="Save data"/><div className="settings-card"><p><Save/> Progress saves automatically on this device.</p><button className="danger-btn" onClick={()=>{if(confirm('Erase this franchise permanently?')){localStorage.removeItem(SAVE_KEY);location.reload()}}}><RotateCcw/> Start over</button></div></div>
    {picker?.type==='cornerstone'&&<PlayerPickerSheet title="Choose cornerstone" note="This choice locks for the current season." players={[...team.roster].sort((a,b)=>rating(b)-rating(a))} selectedId={state.cornerstoneId} onClose={()=>setPicker(null)} onPick={chooseCornerstone}/>} 
    {picker?.type==='artifact'&&<PlayerPickerSheet title={`Equip ${artifactById(picker.artifactId)?.name}`} note="Choosing a player moves the artifact immediately." players={team.roster.filter(p=>artifactById(picker.artifactId)?.roles.includes(p.role)).sort(byPosition)} selectedId={Object.keys(state.artifacts?.equipped||{}).find(pid=>state.artifacts.equipped[pid]===picker.artifactId)} allowEmpty onClose={()=>setPicker(null)} onPick={id=>chooseArtifact(picker.artifactId,id)}/>} 
    {picker?.type==='philosophy'&&<PhilosophySheet selectedId={state.philosophyId} onClose={()=>setPicker(null)} onPick={choosePhilosophy}/>} 
  </>
}

function TeamMark({team,size=''}){if(!team)return null;return <span className={`team-mark ${size}`} style={{'--mark-primary':team.colors?.[0]||'#f1723d','--mark-secondary':team.colors?.[1]||'#173725'}} title={fullTeamName(team)} aria-label={`${fullTeamName(team)} logo`}>{team.mark||team.name?.[0]||'?'}</span>}
function Flow({title,step,onBack,aside,children}){return <div className="flow"><div className="flow-head">{onBack?<button onClick={onBack}><ArrowLeftRight className="back-icon"/></button>:<span/>}<div><small>{step}</small><h1>{title}</h1></div>{aside||<span/>}</div><div className="flow-body">{children}</div></div>}
function Pool({value,label,danger}) {return <div className={`pool ${danger?'danger':''}`}><b>{value}</b><span>{label}</span><i>{Array.from({length:Math.min(value,12)},(_,i)=><em key={i}/>)}</i></div>}
function Choice({player,trait,amount,onOpen,onMinus,onPlus,danger,jackpot}){return <div className={`choice ${jackpot?'jackpot':''}`}><button className="choice-main" onClick={onOpen}><PlayerAvatar player={player} size="small"/><span><b>{player.name}</b><small>{player.position} · Age {player.age} · {fmtTrait(trait)}</small>{jackpot&&<em className="jackpot-inline" title={jackpot.note}><Sparkles/><strong>{jackpot.name}</strong><small>3+ PTS · {jackpot.note}</small></em>}</span><div className="trait-score"><b>{player[trait]}<i>→</i>{danger?Math.max(20,player[trait]-amount):Math.min(player[`${trait}Pot`],player[trait]+amount)}</b><small>{player[`${trait}Pot`]} POT</small></div></button><div className="stepper"><button onClick={onMinus} disabled={!amount}><Minus/></button><b className={danger?'neg':'pos'}>{danger?'-':'+'}{amount}</b><button onClick={onPlus}><Plus/></button></div></div>}
function DuoCard({duo,team}){const players=duo.players.map(id=>team.roster.find(p=>p.id===id)).filter(Boolean);if(players.length<2)return null;return <div className="duo-card"><span className="duo-icon">♣</span><div><small>DYNAMIC DUO</small><b>{duo.name}</b><p>{players.map(p=>p.name).join(' + ')} · {duo.note}</p></div></div>}
function TradePlayer({label,player,onOpen}){return <button className="trade-player" onClick={onOpen}><small>{label}</small><PlayerAvatar player={player} size="medium"/><b>{player.name}</b><span>{player.position} · Age {player.age}</span><div><strong>{rating(player)}</strong><small>OVR</small><strong>{potential(player)}</strong><small>POT</small><strong>{player.salary}M</strong><small>SALARY</small></div></button>}
function PlayerPickerSheet({title,note,players,selectedId,onClose,onPick,allowEmpty=false}){return <div className="sheet-wrap" onClick={onClose}><div className="sheet management-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={onClose}><X/></button><div className="management-head"><small>ROSTER DECISION</small><h2>{title}</h2><p>{note}</p></div><div className="management-player-list">{allowEmpty&&<button className={!selectedId?'selected':''} onClick={()=>onPick('')}><span className="management-empty"><X/></span><span><b>Leave unequipped</b><small>Return the artifact to the vault.</small></span></button>}{players.map(p=><button className={selectedId===p.id?'selected':''} key={p.id} onClick={()=>onPick(p.id)}><PlayerAvatar player={p} size="tiny"/><span><b>{p.name}</b><small>{positionsLabel(p)} · Age {p.age} · {p.salary}M</small></span><em>{rating(p)}<small>OVR</small></em><em>{potential(p)}<small>POT</small></em><ChevronRight/></button>)}</div></div></div>}
function PhilosophySheet({selectedId,onClose,onPick}){return <div className="sheet-wrap" onClick={onClose}><div className="sheet management-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={onClose}><X/></button><div className="management-head"><small>OWNER DIRECTION</small><h2>Change philosophy</h2><p>The new philosophy applies to future development allocations and games.</p></div><div className="philosophy-picker">{philosophies.map(p=><button className={selectedId===p.id?'selected':''} key={p.id} onClick={()=>onPick(p.id)}><i>{p.icon}</i><span><b>{p.name}</b><small>{p.benefit}</small><em>{p.drawback}</em></span>{selectedId===p.id?<ShieldCheck/>:<ChevronRight/>}</button>)}</div></div></div>}
function RosterOverlay({team,onClose}){const players=[...team.roster].sort(byPosition);return <div className="sheet-wrap" onClick={onClose}><div className="sheet roster-overlay" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={onClose}><X/></button><div className="roster-overlay-head"><span><small>POSITION-SORTED</small><h2>My current roster</h2></span><b>{team.roster.length}/20</b></div><div className="roster-overlay-columns"><span>PLAYER</span><span>NOW</span><span>POT</span><span>SAL</span></div><div className="roster-overlay-list">{players.map(p=><div key={p.id}><span className="player-pos">{positionsLabel(p)}</span><PlayerAvatar player={p} size="tiny"/><span><b>{p.name}</b><small>{p.role==='SP'?'Starter':p.role==='RP'?'Reliever':'Position player'}</small></span><em>{rating(p)}</em><em>{potential(p)}</em><em>{p.salary}M</em></div>)}</div></div></div>}
function PlayerSheet({player,team,state,onClose}){
  const traits=player.role==='BAT'?BAT_TRAITS:PITCH_TRAITS,s=statOf(player),artifact=artifactById(state?.artifacts?.equipped?.[player.id]),duo=state?.bonds?.find(d=>d.players.includes(player.id)),extraTraits=[player.signature&&{...player.signature,type:'SIGNATURE TRAIT',icon:'✦'},player.wildCard&&{...player.wildCard,type:'ROOKIE ARCHETYPE',icon:'⚡'}].filter(Boolean);
  return <div className="sheet-wrap" onClick={onClose}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={onClose}><X/></button><div className="player-hero"><PlayerAvatar player={player} size="hero"/><div><span>{positionsLabel(player)} · {player.bats}HB / {player.throws}HP</span><h2>{player.name}</h2><p>{team?fullTeamName(team):'Free agent'} · Age {player.age} · {player.salary}M</p></div><div className="overall"><b>{rating(player)}</b><small>OVR</small></div></div>{player.form!=='neutral'&&<FormBadge form={player.form}/>}<div className="player-tags">{state?.cornerstoneId===player.id&&<span>★ FRANCHISE CORNERSTONE</span>}{artifact&&<span>{artifact.icon} {artifact.name}</span>}{duo&&<span>♣ {duo.name}</span>}{player.labMark&&<span>⌁ LAB MODIFIED</span>}</div>{extraTraits.length>0&&<section className="profile-traits"><header><Sparkles/><span><small>EXTRA PLAYER TRAITS</small><b>{extraTraits.length} UNLOCKED</b></span></header>{extraTraits.map(t=><div key={t.id}><i>{t.icon}</i><span><small>{t.type}</small><b>{t.name}</b><p>{t.note}</p></span></div>)}</section>}{artifact&&<div className="player-effects"><p><b>EQUIPPED · {artifact.name}</b>{artifact.note}</p></div>}<div className="player-stat-strip">{player.role==='BAT'?<><span><small>AVG</small><b>{battingAvg(player)}</b></span><span><small>HR</small><b>{s.hr}</b></span><span><small>OPS</small><b>{playerOps(player)}</b></span></>:<><span><small>K</small><b>{s.k}</b></span><span><small>WHIP</small><b>{playerWhip(player)}</b></span><span><small>ERA</small><b>{playerEra(player)}</b></span></>}</div><div className="trait-list">{traits.map(t=><div key={t}><span>{fmtTrait(t)}</span><b>{player[t]}</b><i><em style={{width:`${player[t]}%`}}/></i><small>{player[`${t}Pot`]} POT</small></div>)}</div><div className="bio-grid"><div><small>ORIGINAL CLUB</small><b>{player.originTeamId==null?'Undrafted':`Team ${player.originTeamId+1}`}</b></div><div><small>TEAM TENURE</small><b>{player.tenure} seasons</b></div><div><small>CHAMPIONSHIPS</small><b>{player.championships}</b></div><div><small>CAREER</small><b>{player.careerSeasons} seasons</b></div></div></div></div>
}
function SubSheet({type,state,matchup,onClose,onPick}){const team=state.league.teams[state.userId],used=state.game.pitcherLog[state.userId];const options=type==='pitcher'?team.roster.filter(p=>(p.role==='RP'||p.role==='SP')&&!used.includes(p.id)):team.roster.filter(p=>p.role==='BAT'&&!state.game.lineups[state.userId].includes(p.id));return <div className="sheet-wrap" onClick={onClose}><div className="sheet small" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><h2>{type==='pitcher'?'Call the bullpen':'Choose a pinch hitter'}</h2><div className="sub-list">{options.map(p=><button key={p.id} onClick={()=>onPick(p.id)}><span className="player-pos">{p.position}</span><span><b>{p.name}</b><small>{type==='pitcher'?`${p.velocity} VEL · ${p.spin} SPN`:`${p.contact} CON · ${p.power} POW`}</small></span><b>{rating(p)}</b><ChevronRight/></button>)}</div>{!options.length&&<p className="flow-copy">No eligible players remain.</p>}</div></div>}
function BaseDiamond({bases,outs}){return <div className="diamond-wrap"><div className="diamond">{[0,1,2].map(b=><i key={b} className={bases[b]?'on':''}/>)}</div><small>{outs} OUT{outs!==1?'S':''}</small></div>}
function FormBadge({form}){return <span className={`form-badge ${form}`}>{form==='hot'?<Flame/>:<Snowflake/>}{form.toUpperCase()}</span>}
function FormDot({form}){return <i className={`form-dot ${form}`}>{form==='hot'?<Flame/>:form==='cold'?<Snowflake/>:null}</i>}
function PlayerAvatar({player,size='small'}){
  const seed=[...(player?.id||player?.name||'player')].reduce((n,c)=>n+c.charCodeAt(0),0),skins=['#f2c9a0','#dca579','#9c6345','#74432f','#e9b889'],hairs=['#251b17','#663b20','#d17b2e','#b5a076','#3b302b'],freeAgentColors=['#f1723d','#2b7650','#3874a8','#9b4e70','#c3a13f'],club=Number.isInteger(player?.teamId)?teamNames[player.teamId]:null;
  const style={'--skin':skins[seed%skins.length],'--hair':hairs[(seed>>2)%hairs.length],'--jersey':club?.colors[0]||freeAgentColors[(seed>>3)%freeAgentColors.length],'--uniform-trim':club?.colors[1]||'#f3f1e9'};
  return <div className={`toon-avatar ${size} face-${seed%5} ${player?.role==='BAT'?'batter':'pitcher'}`} style={style} aria-hidden="true"><i className="cap"/><i className="ear left"/><i className="ear right"/><i className="eye left"/><i className="eye right"/>{seed%3===0&&<i className="glasses"/>}{seed%4===0&&<i className="mustache"/>}<i className="nose"/><i className="mouth"/><i className="jersey"/></div>
}
function SectionTitle({label,action}){return <div className="section-title"><span>{label}</span>{action&&<button>{action}<ChevronRight/></button>}</div>}
function PageHead({kicker,title,meta}){return <div className="page-head"><div><small>{kicker}</small><h1>{title}</h1></div><b>{meta}</b></div>}

export default App;
